name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Replace with your default branch if different

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Auto Merge
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo
            const pr = context.payload.pull_request

            if (pr.user.login === 'dependabot[bot]') {
              try {
                await github.pulls.merge({
                  owner,
                  repo,
                  pull_number: pr.number
                })
                console.log(`Merged PR #${pr.number}`)

                await github.git.deleteRef({
                  owner,
                  repo,
                  ref: `heads/${pr.head.ref}`
                })
                console.log(`Deleted branch ${pr.head.ref}`)
              } catch (error) {
                console.log(`Failed to merge and delete branch for PR #${pr.number}: ${error.message}`)
              }
            }