name: Dependabot auto-approve and merge
on: 
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Merge Dependabot PRs
        run: |
          PRs=$(gh pr list --limit 100 --state open --json number,author --jq '[.[] | select(.author.login == "dependabot[bot]") | .number]')
          if [ -z "$PRs" ]; then
            echo "No open pull requests by Dependabot found."
            exit 0
          fi
          for PR in "${PRs[@]}"
          do
            gh pr merge "$PR" --auto --merge
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
